spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/main_db
    username: ${DB_USER:main}
    password: ${DB_PASSWORD:main}

  sql:
    init:
      mode: always

  jpa:
    open-in-view: false
    properties:
      hibernate:
        ddl-auto: validate

ewm:
  stats-server:
    url: http://stats-server