spring:
  application:
    name: config-server
  profiles:
    include: native
  cloud:
    config:
      retry:
        useRandomPolicy: true
        max-interval: 6000
      server:
        native:
          searchLocations:
            - classpath:config/core
            - classpath:config/core/{application}
            - classpath:config/infra/{application}
            - classpath:config/stats/{application}

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    initial-instance-info-replication-interval-seconds: 10
    instance-info-replication-interval-seconds: 30
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics