x-db-common: &db-common
  image: postgres:16.1-alpine
  restart: unless-stopped
  healthcheck:
    test: ["CMD-SHELL", "pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER"]
    timeout: 5s
    interval: 5s
    retries: 10
    start_period: 10s

services:
  stats-server-db:
    <<: *db-common
    container_name: stats-server-db
    volumes:
      - stats_db_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=stats_db
      - POSTGRES_USER=stats
      - POSTGRES_PASSWORD=stats

  user-service-db:
    <<: *db-common
    container_name: user-service-db
    volumes:
      - user_db_data:/var/lib/postgresql/data/
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=user_service_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user

  event-service-db:
    <<: *db-common
    container_name: event-service-db
    volumes:
      - event_db_data:/var/lib/postgresql/data/
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_DB=event_service_db
      - POSTGRES_USER=event
      - POSTGRES_PASSWORD=event

  request-service-db:
    <<: *db-common
    container_name: request-service-db
    volumes:
      - request_db_data:/var/lib/postgresql/data/
    ports:
      - "5436:5432"
    environment:
      - POSTGRES_DB=request_service_db
      - POSTGRES_USER=request
      - POSTGRES_PASSWORD=request

volumes:
  stats_db_data:
  user_db_data:
  event_db_data:
  request_db_data:
