spring:
  profiles:
    include:
    - db

  datasource:
    url: jdbc:postgresql://postgres:5432/comments_db

logging:
  level:
    org.springframework.cloud.loadbalancer: ERROR

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, beans