spring:
  application:
    name: gateway-server
  config:
    import: "configserver:"
  cloud:
    config:
      retry:
        useRandomPolicy: true
        max-interval: 6000
      discovery:
        enabled: true
        serviceId: config-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: gateway-server

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    gateway:
      enabled: true