spring:
  sql:
    init:
      mode: always
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5432/stats_db
    username: ${DB_USER:user}
    password: ${DB_PASSWORD:password}

logging:
  level:
    org.springframework.cloud.loadbalancer: ERROR
